In [85]:
import pandas as pd

In [86]:
competitions = pd.read_json("../data/raw/competitions.json")

In [87]:
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [88]:
competitions.shape

(80, 12)

In [89]:
competitions.columns

Index(['competition_id', 'season_id', 'country_name', 'competition_name',
       'competition_gender', 'competition_youth', 'competition_international',
       'season_name', 'match_updated', 'match_updated_360',
       'match_available_360', 'match_available'],
      dtype='str')

In [90]:
competitions.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   competition_id             80 non-null     int64
 1   season_id                  80 non-null     int64
 2   country_name               80 non-null     str
 3   competition_name           80 non-null     str
 4   competition_gender         80 non-null     str
 5   competition_youth          80 non-null     bool
 6   competition_international  80 non-null     bool
 7   season_name                80 non-null     str
 8   match_updated              80 non-null     str
 9   match_updated_360          58 non-null     str
 10  match_available_360        12 non-null     str
 11  match_available            80 non-null     str
dtypes: bool(2), int64(2), str(8)
memory usage: 6.5 KB

In [91]:
competitions[["country_name", "competition_name", "season_name"]].head(10)

  country_name        competition_name season_name
0      Germany           1. Bundesliga   2023/2024
1      Germany           1. Bundesliga   2015/2016
2       Africa  African Cup of Nations        2023
3       Europe        Champions League   2018/2019
4       Europe        Champions League   2017/2018
5       Europe        Champions League   2016/2017
6       Europe        Champions League   2015/2016
7       Europe        Champions League   2014/2015
8       Europe        Champions League   2013/2014
9       Europe        Champions League   2012/2013

In [92]:
competitions["country_name"] == "England"

0     False
1     False
2     False
3     False
4     False
      ...
75    False
76    False
77    False
78    False
79    False
Name: country_name, Length: 80, dtype: bool

In [93]:
competitions[competitions["country_name"] == "England"].shape[0]

6

In [94]:
temp = competitions[competitions["country_name"] == "England"]

temp[["competition_name", "season_name"]]

           competition_name season_name
25  FA Women's Super League   2023/2024
26  FA Women's Super League   2020/2021
27  FA Women's Super League   2019/2020
28  FA Women's Super League   2018/2019
68           Premier League   2015/2016
69           Premier League   2003/2004

In [95]:
competitions[competitions["country_name"] == "England"][["competition_name", "season_name"]]

           competition_name season_name
25  FA Women's Super League   2023/2024
26  FA Women's Super League   2020/2021
27  FA Women's Super League   2019/2020
28  FA Women's Super League   2018/2019
68           Premier League   2015/2016
69           Premier League   2003/2004

In [96]:
competitions[(competitions["competition_name"] == "Premier League") & (competitions["season_name"] == "2015/2016")][["competition_id", "season_id", "competition_name", "season_name"]]

    competition_id  season_id competition_name season_name
68               2         27   Premier League   2015/2016

## premier league 2015/2016 Match data

In [97]:
matches = pd.read_json("../data/raw/matches/27.json")

In [98]:
matches.shape

(380, 18)

In [99]:
matches.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_team', 'away_team', 'home_score', 'away_score', 'match_status',
       'match_status_360', 'last_updated', 'last_updated_360', 'metadata',
       'match_week', 'competition_stage', 'stadium', 'referee'],
      dtype='str')

In [100]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           380 non-null    int64
 1   match_date         380 non-null    str
 2   kick_off           380 non-null    str
 3   competition        380 non-null    object
 4   season             380 non-null    object
 5   home_team          380 non-null    object
 6   away_team          380 non-null    object
 7   home_score         380 non-null    int64
 8   away_score         380 non-null    int64
 9   match_status       380 non-null    str
 10  match_status_360   380 non-null    str
 11  last_updated       380 non-null    str
 12  last_updated_360   380 non-null    str
 13  metadata           380 non-null    object
 14  match_week         380 non-null    int64
 15  competition_stage  380 non-null    object
 16  stadium            380 non-null    object
 17  referee            380 non-null    object
dtypes: int64(4), object(8), str(6)
memory usage: 53.6+ KB

In [101]:
matches.head(3)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,3754217,2015-09-19,11:45:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 33, 'home_team_name': 'Chelse...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",2,0,available,scheduled,2025-12-16T17:01:18.696515,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",6,"{'id': 1, 'name': 'Regular Season'}","{'id': 10, 'name': 'Stamford Bridge', 'country...","{'id': 6, 'name': 'Mike Dean', 'country': {'id..."
1,3754117,2015-12-13,12:30:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 59, 'home_team_name': 'Aston ...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",0,2,available,scheduled,2025-12-16T17:04:24.176407,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",16,"{'id': 1, 'name': 'Regular Season'}","{'id': 211, 'name': 'Villa Park', 'country': {...","{'id': 12, 'name': 'Kevin Friend', 'country': ..."
2,3754296,2015-12-21,19:00:00.000,"{'competition_id': 2, 'country_name': 'England...","{'season_id': 27, 'season_name': '2015/2016'}","{'home_team_id': 1, 'home_team_name': 'Arsenal...","{'away_team_id': 36, 'away_team_name': 'Manche...",2,1,available,scheduled,2025-12-17T11:59:35.059270,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",17,"{'id': 1, 'name': 'Regular Season'}","{'id': 3, 'name': 'Emirates Stadium', 'country...","{'id': 5, 'name': 'Andre Marriner', 'country':..."

In [102]:
matches[["match_date", "home_team", "away_team", "home_score", "away_score"]].head()

,match_date,home_team,away_team,home_score,away_score
0,2015-09-19,"{'home_team_id': 33, 'home_team_name': 'Chelse...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",2,0
1,2015-12-13,"{'home_team_id': 59, 'home_team_name': 'Aston ...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",0,2
2,2015-12-21,"{'home_team_id': 1, 'home_team_name': 'Arsenal...","{'away_team_id': 36, 'away_team_name': 'Manche...",2,1
3,2015-10-31,"{'home_team_id': 26, 'home_team_name': 'Swanse...","{'away_team_id': 1, 'away_team_name': 'Arsenal...",0,3
4,2015-12-05,"{'home_team_id': 1, 'home_team_name': 'Arsenal...","{'away_team_id': 41, 'away_team_name': 'Sunder...",3,1

In [103]:
matches["home_team"].iloc[0]

{'home_team_id': 33,
 'home_team_name': 'Chelsea',
 'home_team_gender': 'male',
 'home_team_group': None,
 'country': {'id': 68, 'name': 'England'},
 'managers': [{'id': 383,
   'name': 'José Mario Felix dos Santos Mourinho',
   'nickname': 'José Mourinho',
   'dob': '1963-01-26',
   'country': {'id': 183, 'name': 'Portugal'}}]}

In [104]:
matches["home_team"].iloc[0]["home_team_name"]

'Chelsea'

In [105]:
matches["home_team_name"] = matches["home_team"].apply(
    lambda team: team["home_team_name"]
)

matches["away_team_name"] = matches["away_team"].apply(
    lambda team: team["away_team_name"]
)

In [106]:
matches[["match_date", "home_team_name", "away_team_name", "home_score", "away_score"]].head(10)

   match_date        home_team_name   away_team_name  home_score  away_score
0  2015-09-19               Chelsea          Arsenal           2           0
1  2015-12-13           Aston Villa          Arsenal           0           2
2  2015-12-21               Arsenal  Manchester City           2           1
3  2015-10-31          Swansea City          Arsenal           0           3
4  2015-12-05               Arsenal       Sunderland           3           1
5  2015-08-24               Arsenal        Liverpool           0           0
6  2015-12-26           Southampton          Arsenal           4           0
7  2015-11-29             Liverpool     Swansea City           1           0
8  2016-01-02        Leicester City  AFC Bournemouth           0           0
9  2015-10-17  West Bromwich Albion       Sunderland           1           0

In [107]:
totalGoals = matches["home_score"].sum() + matches["away_score"].sum()

print(totalGoals)

1026

In [108]:
totalGoals = matches["home_score"].sum() + matches["away_score"].sum()

print(totalGoals/(matches.shape[0]))

2.7

In [109]:
homeGoals = matches["home_score"].sum()
awayGoals = matches["away_score"].sum()

print("Home goals:", homeGoals)
print("Away goals:", awayGoals)
print("Difference:", homeGoals - awayGoals)

Home goals: 567
Away goals: 459
Difference: 108

In [110]:
teamName = matches.groupby("home_team_name")
homeGoals = teamName["home_score"].sum()

print(homeGoals.sort_values(ascending=False))

home_team_name
Manchester City         47
Southampton             39
Everton                 35
Leicester City          35
Tottenham Hotspur       35
West Ham United         34
Liverpool               33
Chelsea                 32
Newcastle United        32
Arsenal                 31
Manchester United       27
Norwich City            26
Sunderland              23
AFC Bournemouth         23
Stoke City              22
Watford                 20
West Bromwich Albion    20
Swansea City            20
Crystal Palace          19
Aston Villa             14
Name: home_score, dtype: int64

In [111]:
total = (matches.groupby("home_team_name")["home_score"].sum()) + (matches.groupby("away_team_name")["away_score"].sum())

print(total.sort_values(ascending=False))

home_team_name
Manchester City         71
Tottenham Hotspur       69
Leicester City          68
Arsenal                 65
West Ham United         65
Liverpool               63
Chelsea                 59
Southampton             59
Everton                 59
Manchester United       49
Sunderland              48
AFC Bournemouth         45
Newcastle United        44
Swansea City            42
Stoke City              41
Watford                 40
Norwich City            39
Crystal Palace          39
West Bromwich Albion    34
Aston Villa             27
dtype: int64

In [112]:
home_score = 2
away_score = 0

if home_score > away_score:
    print("Home Win")
elif home_score < away_score:
    print("Away Win")
else:
    print("Draw")

Home Win

In [113]:
def getResult(home_score, away_score):
    if home_score > away_score:
        return "Home Win"
    elif home_score < away_score:
        return "Away Win"
    else:
        return "Draw"

In [114]:
getResult(2, 0)

'Home Win'

In [115]:
matches.iloc[0]

match_id                                                       3754217
match_date                                                  2015-09-19
kick_off                                                  11:45:00.000
competition          {'competition_id': 2, 'country_name': 'England...
season                   {'season_id': 27, 'season_name': '2015/2016'}
home_team            {'home_team_id': 33, 'home_team_name': 'Chelse...
away_team            {'away_team_id': 1, 'away_team_name': 'Arsenal...
home_score                                                           2
away_score                                                           0
match_status                                                 available
match_status_360                                             scheduled
last_updated                                2025-12-16T17:01:18.696515
last_updated_360                               2021-06-13T16:17:31.694
metadata             {'data_version': '1.1.0', 'shot_fidelity_versi...
match_week                                                           6
competition_stage                  {'id': 1, 'name': 'Regular Season'}
stadium              {'id': 10, 'name': 'Stamford Bridge', 'country...
referee              {'id': 6, 'name': 'Mike Dean', 'country': {'id...
home_team_name                                                 Chelsea
away_team_name                                                 Arsenal
Name: 0, dtype: object

In [116]:
matches["result"] = matches.apply(
    lambda row: getResult(row["home_score"], row["away_score"]),
    axis = 1
)

In [117]:
matches[["home_team_name", "away_team_name", "home_score", "away_score", "result"]].head(10)

         home_team_name   away_team_name  home_score  away_score    result
0               Chelsea          Arsenal           2           0  Home Win
1           Aston Villa          Arsenal           0           2  Away Win
2               Arsenal  Manchester City           2           1  Home Win
3          Swansea City          Arsenal           0           3  Away Win
4               Arsenal       Sunderland           3           1  Home Win
5               Arsenal        Liverpool           0           0      Draw
6           Southampton          Arsenal           4           0  Home Win
7             Liverpool     Swansea City           1           0  Home Win
8        Leicester City  AFC Bournemouth           0           0      Draw
9  West Bromwich Albion       Sunderland           1           0  Home Win

In [118]:
homeWins = matches[matches["result"] == "Home Win"]
total = (homeWins.groupby("home_team_name")["result"].count())

print(total.sort_values(ascending=False))

home_team_name
Arsenal                 12
Manchester United       12
Manchester City         12
Leicester City          12
Southampton             11
Tottenham Hotspur       10
West Ham United          9
Stoke City               8
Swansea City             8
Liverpool                8
Newcastle United         7
Everton                  6
Norwich City             6
Sunderland               6
Watford                  6
Crystal Palace           6
West Bromwich Albion     6
AFC Bournemouth          5
Chelsea                  5
Aston Villa              2
Name: result, dtype: int64

In [119]:
awayWins = matches[matches["result"] == "Away Win"]
total = (awayWins.groupby("away_team_name")["result"].count())

print(total.sort_values(ascending=False))

away_team_name
Leicester City          11
Tottenham Hotspur        9
Arsenal                  8
Liverpool                8
Southampton              7
West Ham United          7
Chelsea                  7
Manchester United        7
Manchester City          7
AFC Bournemouth          6
Watford                  6
Stoke City               6
Everton                  5
Crystal Palace           5
West Bromwich Albion     4
Swansea City             4
Sunderland               3
Norwich City             3
Newcastle United         2
Aston Villa              1
Name: result, dtype: int64

In [120]:
totalHomeWins = homeWins.groupby("home_team_name")["result"].count()
totalAwayWins = awayWins.groupby("away_team_name")["result"].count()
totalWins =  totalHomeWins + totalAwayWins

print(totalWins.sort_values(ascending=False))

home_team_name
Leicester City          23
Arsenal                 20
Manchester City         19
Manchester United       19
Tottenham Hotspur       19
Southampton             18
Liverpool               16
West Ham United         16
Stoke City              14
Watford                 12
Chelsea                 12
Swansea City            12
Everton                 11
AFC Bournemouth         11
Crystal Palace          11
West Bromwich Albion    10
Norwich City             9
Newcastle United         9
Sunderland               9
Aston Villa              3
Name: result, dtype: int64

In [121]:
draws = matches[matches["result"] == "Draw"]
totalHomeTeamDraws = draws.groupby("home_team_name")["result"].count()
totalAwayTeamDraws = draws.groupby("away_team_name")["result"].count()

totalDraws = totalHomeTeamDraws + totalAwayTeamDraws
print(totalDraws.sort_values(ascending=False))

home_team_name
Chelsea                 14
Everton                 14
West Ham United         14
Tottenham Hotspur       13
West Bromwich Albion    13
Sunderland              12
Liverpool               12
Leicester City          12
Arsenal                 11
Swansea City            11
Newcastle United        10
AFC Bournemouth          9
Southampton              9
Manchester United        9
Manchester City          9
Crystal Palace           9
Watford                  9
Stoke City               9
Aston Villa              8
Norwich City             7
Name: result, dtype: int64

In [122]:
totalLosses = 38 - totalWins - totalDraws

print(totalLosses.sort_values(ascending=True))

home_team_name
Leicester City           3
Tottenham Hotspur        6
Arsenal                  7
West Ham United          8
Manchester United       10
Manchester City         10
Liverpool               10
Southampton             11
Chelsea                 12
Everton                 13
Swansea City            15
Stoke City              15
West Bromwich Albion    15
Watford                 17
Sunderland              17
AFC Bournemouth         18
Crystal Palace          18
Newcastle United        19
Norwich City            22
Aston Villa             27
Name: result, dtype: int64

In [123]:
table = pd.DataFrame({
    "Wins": totalWins,
    "Draws": totalDraws,
    "Losses": totalLosses
})

table.head(20)

                      Wins  Draws  Losses
home_team_name
AFC Bournemouth         11      9      18
Arsenal                 20     11       7
Aston Villa              3      8      27
Chelsea                 12     14      12
Crystal Palace          11      9      18
Everton                 11     14      13
Leicester City          23     12       3
Liverpool               16     12      10
Manchester City         19      9      10
Manchester United       19      9      10
Newcastle United         9     10      19
Norwich City             9      7      22
Southampton             18      9      11
Stoke City              14      9      15
Sunderland               9     12      17
Swansea City            12     11      15
Tottenham Hotspur       19     13       6
Watford                 12      9      17
West Bromwich Albion    10     13      15
West Ham United         16     14       8

In [125]:
table["Points"] = table["Wins"] * 3 + table["Draws"]

table = table.sort_values(by="Points", ascending=False)
table.head(20)

                      Wins  Draws  Losses  Points
home_team_name
Leicester City          23     12       3      81
Arsenal                 20     11       7      71
Tottenham Hotspur       19     13       6      70
Manchester United       19      9      10      66
Manchester City         19      9      10      66
Southampton             18      9      11      63
West Ham United         16     14       8      62
Liverpool               16     12      10      60
Stoke City              14      9      15      51
Chelsea                 12     14      12      50
Swansea City            12     11      15      47
Everton                 11     14      13      47
Watford                 12      9      17      45
West Bromwich Albion    10     13      15      43
Crystal Palace          11      9      18      42
AFC Bournemouth         11      9      18      42
Sunderland               9     12      17      39
Newcastle United         9     10      19      37
Norwich City             9      7      22      34
Aston Villa              3      8      27      17

In [128]:
homeGoalsByTeam = matches["home_score"].sum()
awayGoalsByTeam = matches["away_score"].sum()

goalsFor = homeGoalsByTeam + awayGoalsByTeam

print(goalsFor)

1026